services:
  postgres:
    image: postgres:16
    container_name: clinical_notes_db
    environment:
      POSTGRES_DB: clinical_notes
      POSTGRES_USER: catarina
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: clinical_notes_app
    ports:
      - "8181:8181"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/clinical_notes
      SPRING_DATASOURCE_USERNAME: catarina
      SPRING_DATASOURCE_PASSWORD: password123
    depends_on:
      - postgres